name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: harehare/setup-mq@cfe56378737401938b84d329d42f63cafa263a71 # v1.1.6
        with:
          bins: test
      - name: Run tests
        run: mq-test qrcode_tests.mq
